# Generated by Django 4.0.3 on 2022-11-18 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('slug', models.SlugField(max_length=255)),
                ('road', models.CharField(max_length=500)),
                ('alias', models.CharField(blank=True, max_length=250)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPermisson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analythics', models.BooleanField(default=False)),
                ('products_edit', models.BooleanField(default=False)),
                ('products_delete', models.BooleanField(default=False)),
                ('migration', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('shop_main', models.BooleanField(default=False)),
                ('shop_info', models.BooleanField(default=False)),
                ('shop_team', models.BooleanField(default=False)),
                ('shop_messages', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('100_free', '100% free'), ('100_free_premium', '100% free premium'), ('personal_use', 'personal use'), ('commercial_use', 'commercial use'), ('extended_commercial', 'extended commercial')], max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_lisence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_date', models.DateField(auto_now_add=True)),
                ('product_file', models.FileField(null=True, upload_to=mainapp.models.product_file_path)),
                ('file_size', models.CharField(blank=True, max_length=30, null=True)),
                ('orig_link', models.CharField(blank=True, max_length=100, null=True)),
                ('file_type', models.CharField(max_length=10)),
                ('portfolio_link', models.CharField(blank=True, max_length=150, null=True)),
                ('parse_descr', models.TextField(blank=True, max_length=67000, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=125, null=True)),
                ('seo_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('descr', models.TextField(blank=True, max_length=67000, null=True)),
                ('public_status', models.CharField(choices=[('pending_approval', 'pending approval'), ('rejected', 'rejected'), ('published', 'published'), ('draft', 'quarantined')], max_length=50)),
                ('private_status', models.CharField(choices=[('hide', 'hide'), ('accepted', 'accepted'), ('new', 'new'), ('in_sorting', 'in sorting'), ('quarantined', 'quarantined')], max_length=50)),
                ('accepted', models.BooleanField(default=True)),
                ('reject_comment', models.TextField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_alias', models.CharField(blank=True, max_length=255)),
                ('properties', models.CharField(blank=True, max_length=255, null=True)),
                ('migration', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='mainapp.category')),
                ('license', models.ManyToManyField(blank=True, null=True, related_name='product_licenses', to='mainapp.license')),
                ('likes', models.ManyToManyField(related_name='product_likes', to=settings.AUTH_USER_MODEL)),
                ('manual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_manual', to='mainapp.manual')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('indexed', 'indexed'), ('not_indexed', 'not indexed'), ('not_considered', 'not considered')], default='not considered', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('indexed', 'indexed'), ('not_indexed', 'not indexed'), ('not_considered', 'not considered')], default='not considered', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('descr', models.TextField(blank=True, max_length=1000, null=True)),
                ('alias', models.CharField(max_length=125)),
                ('shop_logo', models.ImageField(blank=True, null=True, upload_to='shop/logo/%Y/%m/%d/')),
                ('shop_banner', models.ImageField(blank=True, null=True, upload_to='shop/banner/%Y/%m/%d/')),
                ('assistants', models.ManyToManyField(blank=True, null=True, related_name='shop_assistants', to=settings.AUTH_USER_MODEL)),
                ('custom_rules', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_custom_users', to='mainapp.custompermisson')),
                ('followers', models.ManyToManyField(related_name='shop_followers', to=settings.AUTH_USER_MODEL)),
                ('managers', models.ManyToManyField(blank=True, null=True, related_name='shop_managers', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='shop_owner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='shop_custom_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ_sales', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('products', models.ManyToManyField(related_name='products_sales', to='mainapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', mainapp.models.IntegerRangeField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='mainapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='mainapp.shop'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='mainapp.tag'),
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_image', to='mainapp.image')),
                ('images', models.ManyToManyField(related_name='presentation_images', to='mainapp.image')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_presentations', to='mainapp.product')),
            ],
            options={
                'verbose_name': 'Presentation',
                'verbose_name_plural': 'Presentations',
            },
        ),
        migrations.AddField(
            model_name='license',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lisences', to='mainapp.product'),
        ),
        migrations.CreateModel(
            name='HintChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'new'), ('skipped', 'skipped'), ('done', 'done')], default='new', max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_shops', to='mainapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('finish_date', models.DateTimeField()),
                ('percent_discount', models.IntegerField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_deals', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participants_deals', to=settings.AUTH_USER_MODEL)),
                ('products_enter', models.ManyToManyField(related_name='products_deals_enter', to='mainapp.product')),
                ('products_payable', models.ManyToManyField(related_name='products_deals_payable', to='mainapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
