# Generated by Django 4.0.3 on 2022-11-24 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_manual', to='mainapp.manual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='private_status',
            field=models.CharField(choices=[('hide', 'hide'), ('accepted', 'accepted'), ('new', 'new'), ('in_sorting', 'in sorting'), ('quarantined', 'quarantined')], default='hide', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_status',
            field=models.CharField(choices=[('pending_approval', 'pending approval'), ('rejected', 'rejected'), ('published', 'published'), ('draft', 'quarantined')], default='pending_approval', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='mainapp.shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='mainapp.tag'),
        ),
    ]
