# Generated by Django 4.0.3 on 2022-11-24 10:02

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_product_likes_alter_product_manual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_file',
            field=models.FileField(blank=True, null=True, upload_to=mainapp.models.product_file_path),
        ),
    ]
